[tool.poetry]
name = "algorithms-and-python-code"
version = "0.1.0"
description = ""
authors = ["owwwl666 <zaharsalam228@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
